_target_: src.models.aggregated.XGBRegressor.model.XGBRegressorModelConfig
name: XGBRegressor
version: default
n_lags: 3
n_estimators: 50
max_depth: 3
learning_rate: 0.02
validation_size: 0.12
random_state: 1337