optuna:
  n_trials: 50
  timeout: 14400
  direction: minimize
  seed: 42

search_space:
  n_lags:
    type: int
    low: 8
    high: 24
  max_depth:
    type: int
    low: 1
    high: 10
  n_estimators:
    type: int
    low: 50
    high: 150
  learning_rate: 
    type: float
    low: 1e-3
    high: 0.05
    log: True